import type {
  BoiPortfolioRecord,
  BoiStatePlacement,
  GeoTrendSnapshotRecord,
} from "@/data/mockData";
import { buildGeoSpreadInsights } from "@/lib/geoSpreadAnalytics";

export type KpiStatus = "on_track" | "watch" | "off_track";
export type KpiTargetType = "min" | "max" | "range";
export type KpiUnit = "count" | "percent" | "currency" | "ratio";

export interface KpiDefinition {
  kpiId:
    | "job_creation"
    | "institutional_growth"
    | "gender_parity"
    | "geographic_spread"
    | "economic_contribution"
    | "startup_survival_12_24m";
  label: string;
  description: string;
  unit: KpiUnit;
  targetType: KpiTargetType;
  target: number;
  owner: "BOI" | "Admin" | "Program Management";
  updateCadence: "monthly" | "quarterly";
  source: string;
  formula: string;
}

export interface KpiSnapshot {
  kpiId: KpiDefinition["kpiId"];
  label: string;
  unit: KpiUnit;
  target: number;
  actual: number;
  variance: number;
  status: KpiStatus;
}

export interface KpiTrendPoint {
  month: string;
  jobsCreated: number;
  genderParity: number;
  geographicSpread: number;
}

export interface KpiFramework {
  definitions: KpiDefinition[];
  snapshots: KpiSnapshot[];
  trend: KpiTrendPoint[];
  breakdownByState: KpiBreakdownRecord[];
  breakdownByCohort: KpiBreakdownRecord[];
  breakdownBySector: KpiBreakdownRecord[];
  targetHistory: KpiTargetRevision[];
  generatedAt: string;
}

export interface KpiBreakdownRecord {
  label: string;
  startups: number;
  jobsCreated: number;
  complianceRate: number;
  femaleLedSharePct: number;
}

export interface KpiTargetRevision {
  kpiId: KpiDefinition["kpiId"];
  previousTarget: number;
  nextTarget: number;
  changedAt: string;
  reason: string;
  changedBy: string;
}

const KPI_DEFINITIONS: KpiDefinition[] = [
  {
    kpiId: "job_creation",
    label: "Job Creation",
    description: "Total jobs generated by supported startups.",
    unit: "count",
    targetType: "min",
    target: 1000,
    owner: "BOI",
    updateCadence: "monthly",
    source: "iDICE portfolio jobs feed",
    formula: "sum(jobsCreated)",
  },
  {
    kpiId: "institutional_growth",
    label: "Institutional Growth Index",
    description: "Composite index of startup activity and governance quality.",
    unit: "percent",
    targetType: "min",
    target: 70,
    owner: "Program Management",
    updateCadence: "monthly",
    source: "portfolio activity and compliance",
    formula: "0.35*activity + 0.4*compliance + 0.25*grant unlock",
  },
  {
    kpiId: "gender_parity",
    label: "Gender Parity",
    description: "Female-led startup share across supported portfolio.",
    unit: "percent",
    targetType: "min",
    target: 50,
    owner: "Admin",
    updateCadence: "quarterly",
    source: "state spread data",
    formula: "femaleLedStartups / totalStartups",
  },
  {
    kpiId: "geographic_spread",
    label: "Geographic Spread",
    description: "Coverage of states with active startup support.",
    unit: "percent",
    targetType: "min",
    target: 50,
    owner: "BOI",
    updateCadence: "monthly",
    source: "state spread data",
    formula: "activeStates / 37",
  },
  {
    kpiId: "economic_contribution",
    label: "Economic Contribution (Proxy)",
    description: "Proxy estimate of portfolio economic value contribution.",
    unit: "currency",
    targetType: "min",
    target: 1500000,
    owner: "Program Management",
    updateCadence: "quarterly",
    source: "jobs, placements and startup activity",
    formula: "jobs*1300 + placements*250 + activeStartups*18000",
  },
  {
    kpiId: "startup_survival_12_24m",
    label: "Startup Survival 12-24m (Proxy)",
    description: "Proxy for startup continuity over the 12-24 month window.",
    unit: "percent",
    targetType: "min",
    target: 65,
    owner: "BOI",
    updateCadence: "quarterly",
    source: "state spread startup continuity proxy",
    formula: "activeStartups / totalStartups",
  },
];

const KPI_TARGET_HISTORY: KpiTargetRevision[] = [
  {
    kpiId: "job_creation",
    previousTarget: 900,
    nextTarget: 1000,
    changedAt: "2026-01-15",
    reason:
      "Adjusted for expanded cohort size and private capital leverage goals.",
    changedBy: "BOI Strategy Office",
  },
  {
    kpiId: "gender_parity",
    previousTarget: 45,
    nextTarget: 50,
    changedAt: "2026-02-03",
    reason:
      "Aligned with inclusion mandate and dedicated women-led startup budget.",
    changedBy: "Program Governance Council",
  },
  {
    kpiId: "geographic_spread",
    previousTarget: 40,
    nextTarget: 50,
    changedAt: "2026-02-21",
    reason: "Decentralization target raised to improve 36-state participation.",
    changedBy: "iDICE Steering Committee",
  },
  {
    kpiId: "startup_survival_12_24m",
    previousTarget: 60,
    nextTarget: 65,
    changedAt: "2026-03-05",
    reason: "Raised after operational support upgrades across funded startups.",
    changedBy: "BOI Delivery PMO",
  },
];

function classifyStatus(
  actual: number,
  target: number,
  targetType: KpiTargetType,
): KpiStatus {
  if (targetType === "min") {
    if (actual >= target) return "on_track";
    if (actual >= target * 0.9) return "watch";
    return "off_track";
  }

  if (targetType === "max") {
    if (actual <= target) return "on_track";
    if (actual <= target * 1.1) return "watch";
    return "off_track";
  }

  return "watch";
}

export function buildIdiceKpiFramework(params: {
  portfolio: BoiPortfolioRecord[];
  geoSpread: BoiStatePlacement[];
  geoTrend: GeoTrendSnapshotRecord[];
  startupSectors?: Record<string, string>;
}): KpiFramework {
  const geo = buildGeoSpreadInsights(params.geoSpread, {
    alertLimit: 10,
    topLimit: 12,
  });
  const jobsCreated = params.portfolio.reduce(
    (sum, item) => sum + item.jobsCreated,
    0,
  );
  const complianceVerified = params.portfolio.filter(
    (item) => item.compliance === "Verified",
  ).length;
  const unlockedGrants = params.portfolio.filter(
    (item) => item.grantStatus === "Unlocked",
  ).length;
  const startupCount = params.portfolio.length;

  const complianceScore =
    startupCount === 0 ? 0 : (complianceVerified / startupCount) * 100;
  const unlockScore =
    startupCount === 0 ? 0 : (unlockedGrants / startupCount) * 100;
  const activityScore = Math.min(100, startupCount * 8);
  const institutionalGrowth = Math.round(
    activityScore * 0.35 + complianceScore * 0.4 + unlockScore * 0.25,
  );

  const genderParity = geo.summary.femaleLedSharePct;
  const geographicSpread = geo.summary.coveragePct;

  const economicContribution =
    jobsCreated * 1300 +
    params.portfolio.reduce((sum, item) => sum + item.talentPlaced, 0) * 250 +
    params.geoSpread.reduce((sum, item) => sum + item.activeStartups, 0) *
      18000;

  const activeStartups = params.geoSpread.reduce(
    (sum, item) => sum + item.activeStartups,
    0,
  );
  const baselineStartups = params.geoSpread.reduce(
    (sum, item) => sum + Math.max(item.totalStartups, 0),
    0,
  );
  const startupSurvival =
    baselineStartups === 0
      ? 0
      : Math.round((activeStartups / baselineStartups) * 100);

  const values: Record<KpiDefinition["kpiId"], number> = {
    job_creation: jobsCreated,
    institutional_growth: institutionalGrowth,
    gender_parity: genderParity,
    geographic_spread: geographicSpread,
    economic_contribution: Math.round(economicContribution),
    startup_survival_12_24m: startupSurvival,
  };

  const snapshots: KpiSnapshot[] = KPI_DEFINITIONS.map((def) => {
    const actual = values[def.kpiId];
    return {
      kpiId: def.kpiId,
      label: def.label,
      unit: def.unit,
      target: def.target,
      actual,
      variance: Number((actual - def.target).toFixed(2)),
      status: classifyStatus(actual, def.target, def.targetType),
    };
  });

  const trend: KpiTrendPoint[] = params.geoTrend.map((point) => ({
    month: point.month,
    jobsCreated: point.jobsCreated,
    genderParity: point.femaleLedSharePct,
    geographicSpread: point.coveragePct,
  }));

  const stateMap = new Map<string, KpiBreakdownRecord>();
  params.geoSpread.forEach((item) => {
    const stateJobs = params.portfolio
      .filter((entry) => entry.state === item.state)
      .reduce((sum, entry) => sum + entry.jobsCreated, 0);
    const femaleLedSharePct =
      item.totalStartups === 0
        ? 0
        : Math.round((item.femaleLedStartups / item.totalStartups) * 100);
    stateMap.set(item.state, {
      label: item.state,
      startups: item.activeStartups,
      jobsCreated: stateJobs,
      complianceRate: item.complianceRate,
      femaleLedSharePct,
    });
  });

  const cohortMap = new Map<string, KpiBreakdownRecord>();
  params.portfolio.forEach((item) => {
    const existing = cohortMap.get(item.cohort) ?? {
      label: item.cohort,
      startups: 0,
      jobsCreated: 0,
      complianceRate: 0,
      femaleLedSharePct: 0,
    };
    existing.startups += 1;
    existing.jobsCreated += item.jobsCreated;
    existing.complianceRate += item.compliance === "Verified" ? 100 : 0;
    cohortMap.set(item.cohort, existing);
  });
  const breakdownByCohort = Array.from(cohortMap.values()).map((item) => ({
    ...item,
    complianceRate:
      item.startups === 0 ? 0 : Math.round(item.complianceRate / item.startups),
  }));

  const sectorMap = new Map<string, KpiBreakdownRecord>();
  params.portfolio.forEach((item) => {
    const sector = params.startupSectors?.[item.startup] ?? "Unknown";
    const existing = sectorMap.get(sector) ?? {
      label: sector,
      startups: 0,
      jobsCreated: 0,
      complianceRate: 0,
      femaleLedSharePct: 0,
    };
    existing.startups += 1;
    existing.jobsCreated += item.jobsCreated;
    existing.complianceRate += item.compliance === "Verified" ? 100 : 0;
    sectorMap.set(sector, existing);
  });
  const breakdownBySector = Array.from(sectorMap.values()).map((item) => ({
    ...item,
    complianceRate:
      item.startups === 0 ? 0 : Math.round(item.complianceRate / item.startups),
  }));

  const breakdownByState = Array.from(stateMap.values()).sort(
    (a, b) => b.jobsCreated - a.jobsCreated,
  );

  return {
    definitions: KPI_DEFINITIONS,
    snapshots,
    trend,
    breakdownByState,
    breakdownByCohort,
    breakdownBySector,
    targetHistory: KPI_TARGET_HISTORY,
    generatedAt: new Date().toISOString(),
  };
}
